const images = {
  backAndroid: require('./back-android.png'),
  backIos: require('./back-ios.png'),
  calendar: require('./calendar.png'),
  checkboxActive: require('./checkbox-active.png'),
  checkboxInactive: require('./checkbox-inactive.png'),
  copy: require('./copy.png'),
  delete: require('./delete.png'),
  dropdown: require('./dropdown.png'),
  enFlag: require('./en-flag.png'),
  esFlag: require('./sp-flag.png'),
  harvestInactive: require('./harvest-active.png'),
  harvestActive: require('./harvest.png'),
  headLogo: require('./head-logo.png'),
  jobReportActive: require('./job-report-active.png'),
  jobReportInactive: require('./job-report-inactive.png'),
  jobSelectionActive: require('./job-selection-active.png'),
  jobSelectionInactive: require('./job-selection-inactive.png'),
  logout: require('./logout.png'),
  logo: require('./logo.png'),
  nextArrow: require('./next-arrow.png'),
  tempWorkersActive: require('./temp-workers-active.png'),
  tempWorkersInactive: require('./temp-workers-inactive.png'),
  tractorInactive: require('./tractor-active.png'),
  tractorActive: require('./tractor.png'),
  trellisInactive: require('./trellis-active.png'),
  trellisActive: require('./trellis.png'),
  vinesInactive: require('./vines-active.png'),
  vinesActive: require('./vines.png'),
};
export default images;
